version: "3.8"
services:
  geo-postgres:
    image: postgis/postgis:16-master
    ports:
      - '5460:5432'
    environment:
      POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL
      POSTGRES_DB: groupfinder
      POSTGRES_USER: username
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
